### ISSUE TITLE
Binary doesnt seem to work

### ISSUE THREAD

**Issue by sweetsamy21** [imagemin/imagemin-pngquant#40]
Hi there,

I installed the above plugin and used it in my gulp task to minify images. works like a charm on my local machine. When I deploy the same code in production environment, I get the following issues. Please help...!!

/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly

Error: pngquant failed to build, make sure that libpng-dev is installed

Do I have to add another npm like libpng-dev in my package.json?

**Comment by jagged3dge** [comment]
`libpng-dev` is a **linux** package. It is required to build/compile the binary executable of `pngquant` on your production box during the package's installation phase. This binary executable is re-built at every fresh installation of a version the npm package because it uses native OS C++ bindings to fully optimize the minification process.

You may look up the docs of your deployment machine's OS flavour for whichever package manager is used to install the `libpng-dev` package before you try to install this lib via npm.

For example, on CentOS/RHEL, you'd use `yum` package manager, like `sudo yum install libpng-dev`, wait for it to complete, then do `npm install`. On Ubuntu, you'd use `sudo apt install libpng-dev`, then `npm-install`.

**Comment by francosalcedo** [comment]
reboot it worked for me <3 !

**Comment by thegbom** [comment]
I upgraded ubuntu, and upgraded npm and node. Then it worked just fine.

**Comment by natanr123** [comment]
I am not sure it is related but the problem was solved for me after adding .dockerignore with node_modules
